plugins {
    id 'com.android.application'
}

android {
    namespace 'com.monitor.phoneguard'
    compileSdk 34

    defaultConfig {
        applicationId "com.monitor.phoneguard"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 순수 안드로이드 SDK 내장 클래스만 사용하여 라이브러리 충돌을 원천 차단합니다.
}
