plugins {
    id 'com.android.application'
}

android {
    namespace 'com.monitor.phoneguard'
    compileSdk 34

    defaultConfig {
        applicationId "com.monitor.phoneguard"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
